- _posts/help/1970-01-01-ubuntu.md
According to Canonical, they don't care whether user use mirror or official security mirror.
> Reverse security repos.

- _posts/help/1970-01-01-archlinuxcn.md
> since all packages are signed, default value for SigLevel (Required
DatabaseOptional) is better. -- lilydjwg
see also: archlinuxcn/repo#218
> Remove siglevel from archlinuxcn mirror config

- _posts/help/1970-01-01-gitlab-ce.md
GitLab has added support for Debian Stretch, and it's already in the mirror (I've been using it).
I've tested the page on my PC, hopefully everything works.
Thank you guys, great work!
> Add debian stretch to gitlab-ce help

- _posts/help/1970-01-01-anaconda.md
If no main channel, upgrade to anaconda 5 would not work from this mirror.
> Add main channel and some 3rd-party

- _posts/help/1970-01-01-anaconda.md
先添加 free频道，后添加 main 频道，使main排在前面，调高优先级。
根据 [Anaconda 文档](https://docs.anaconda.com/anaconda/release-notes)，main 频道默认拥有 top priority. 
调整之前 `.condarc` 文件：
```
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
- defaults
show_channel_urls: true
```
调整之后：
```
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- defaults
show_channel_urls: true
```
> 调高main频道优先级顺序

- _posts/help/1970-01-01-anaconda.md
As win-64 has been released in official pytorch repo since 0.4.0.
> mark anaconda repo of peterjc123 legacy

- _posts/help/1970-01-01-docker-ce.md
Vue processes all {{ x }}. So /static/js/help.js:update_apt_file will
never get literal '{{ release_name }}', leading to wrong rendering.
Bug: https://groups.google.com/forum/#!topic/tuna-general/oFZ0v78hYPc
Reported-By: windforce17
Signed-off-by: Xiami <i@f2light.com>
> help: docker-ce: Fix wrong rendering on centos/fedora distro switch

- _posts/help/1970-01-01-termux.md
Termux已经不再需要原先繁琐的换源方式，直接使用sed替换即可
> 简化Termux使用帮助

- _posts/help/1970-01-01-termux.md
Termux 官方已将软件源迁移至 Bintray，软件源地址也发生了变化
See :
https://github.com/termux/termux-packages/commit/99134641d625f7d9d8735f299802857b31ea0a55
https://github.com/termux/termux-packages/commit/c7b1632e32804e1648ef51a3733afc755a75d153
https://github.com/termux/termux-packages/commit/f780fde2e7b0ac16ec21ac7ce8a41a4ef62267e5
> 更新 Termux 官方源地址

- _posts/help/1970-01-01-hackage.md
- _posts/help/1970-01-01-stackage.md
根据 https://github.com/tuna/mirror-web/issues/132 ，stack v2.1.1增加了若干安全机制，相应地`config.yaml`文件的要求也改变了。
这里依照官方文档进行了修订。但需要tuna镜像同步好新增机制后，才能测试修订是否有效(Also see: https://github.com/tuna/tunasync-scripts/pull/37 )。由于缺少必要的环境，还请其他更方便的同学帮忙测试。
Refs:
* https://docs.haskellstack.org/en/stable/yaml_configuration/#package-indices
* https://docs.haskellstack.org/en/stable/yaml_configuration/#urls
> Update docs for stack v2.1.1 .

- _posts/help/1970-01-01-termux.md
经测试，`pkg up`所造成的很多玄学错误可有`apt update && apt upgrade`解决😂
（应该是`apt full-upgrade`覆盖了一些库的原因）
> Fix termux upgrade error

- _posts/help/1970-01-01-git-repo.md
REPO_URL ends with `/` will make repo fail
see https://github.com/tuna/issues/issues/676
> fix help for git-repo

- _posts/help/2020-02-21-gentoo-prefix.md
Add help about setting mirror when bootstrapping. 
When bootstrapping one needs to download files from multiple sources, the three main sources are gentoo distfiles, gnu and gentoo snapshots. The variables corresponding to them are independent in the bootstrap script, thus they need to be set separately.
> Update Gentoo Prefix Bootstrap Mirror Info

- _posts/help/1970-01-01-fedora.md
Fedora 29 and older are not supported anymore.
> update help page of fedora 

- geninfo/genisolist.ini
1. Images for an unreleased version may appear. Before the format change, the upstream image name had a release number and we filtered out `beta` releases. Currently we work around this by listing two versions and relying on the user to pick the right one.
2. Add small channel.
For the actual syncing I don't know how to configure this, but nixos-images should contain these files:
```plain
s3://nix-channels/nixos-\d\d.\d\d(-small)?/latest-nixos-(\w+)-(i686|x86_64)-linux.(\w+)(.sha256)?
```
> NixOS new release format, take two

- _posts/help/1970-01-01-debian.md
WSL安装的Debian默认不带`ca-certificates`，直接换源会报错：`No system certificates available`
> help: Debian: add ca-certificates for WSL

- _posts/help/2017-12-29-gentoo-portage.md
增加了对 repo 的配置(使得 `emerge --sync` 从 tuna 镜像仓库进行同步)
去除了 eix 相关内容(eix 并非系统自带,相关内容可能会给未安装 eix 的用户带来困扰)
> gentoo-portage帮助文档的修改

- _posts/help/2017-12-29-gentoo-portage.md
- _posts/help/2020-02-21-gentoo-prefix.md
- _posts/help/2020-05-05-gentoo-portage.git.md
Add instructions to enable/update git sync method for Gentoo portage repo.
Note that this pull request is not yet in good shape.  Waiting for @Harry-Chen to:
> Update Gentoo help document

- _layouts/index.html
镜像列表中的帮助链接目前为单个Font Awsome标志，对于命令行浏览器和屏幕阅读器用户并不友好。此PR为其添加了`sr-only`的文字替代。`sr-only`类由bootstrap定义，在支持CSS的现代浏览器中不会显示，但在不支持CSS `clip`的命令行浏览器和屏幕阅读器中会正常工作。
参见：
* [Bootstrap Screenreaders](https://getbootstrap.com/docs/4.0/utilities/screenreaders/)
* [FontAwsome Accessibility](https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility)
修改前在`elinks`中的效果：
修改后：
> 改进镜像列表中的帮助链接

- geninfo/genisolist.ini
实在是不太熟悉regex 😂 ... 之前的匹配忘记检查结尾了，所以导致 asc 文件也被匹配到了
> fix julia regex to not match *.asc files

- _posts/help/2020-05-25-julia.md
- _posts/help/2020-06-05-julia-general.git.md
> 但是这样一来，在**使用旧版本 Julia 时就会因为不兼容而无法更新注册表**，因此最好根据自己的使用场景来确定是否要这样做。
实际上，若能够提供一个 General 的镜像仓库的话，可以通过下面这种方式来添加 git repo 形式的 General，这样就能避免 <=1.3 的 Julia 版本无法更新注册表的问题。
```julia
(@v1.4) pkg>  ]registry add http://mirrors.bfsu.edu.cn/julia/static/registries/General.git/
```
目前国内有的 General repo 镜像：
* USTC: http://mirrors.ustc.edu.cn/julia/registries/General.git/
* Gitee: https://gitee.com/JohnnyChen94/General （我个人维护的）
但我不太确定把这些非TUNA镜像的使用添加到这里是否合适。不知道能不能在 BFSU 上再额外提供一个 git repo 的镜像（不太清楚这种镜像该怎么部署到nginx上）？
CRef: https://github.com/JuliaLang/Pkg.jl/issues/1845
> [julia] use built-in registry functionality to re-pull General

- geninfo/genisolist.ini
Hi, 
我是一个 Debian 用户，在使用镜像站的下载链接列表的时候没有发现 Debian netinst 镜像，
所以在这里添加了一个。平时获取的都是 netinst 镜像，但需要手动导航到相应目录
下载。
祝好。
> Add Debian netinst into download list

- geninfo/genisolist.ini
Add Debian {netinst,dvd,live} with non-free firmware to a separate distribution tab.
> Add Debian NonFree

- geninfo/genisolist.ini
The previous version actually captures RC and beta versions, but display
it incorrectly. This commit fixes the regex to display the rc/beta suffix.
这里实际上有一个显示的错误：应该应该显示 1.5.0-rc1 和 1.5.0-beta1 的
> [julia] display rc version suffixes in genisolist

- geninfo/genisolist.ini
This reverts commit 9fdf2a4e8e34bf26db05cd9bac03a868eb709783 because it fails to sort versions correctly if we include rc versions
匹配rc版本之后大概因为排序的原因没有把 `1.2.0` 正式版给显示出来，所以这次直接不匹配rc和测试版
本地好像没办法直接生成数据，所以只能反复尝试... 希望这是最后一次调整
> [julia] do not capture test and rc versions 

- geninfo/genisolist.ini
platform应该是 `$sys/$arch` 这种，#206 里误操作把它改成 `$sys/$version` 了
> [julia] fix platform label in genisolist

- geninfo/genisolist.ini
`deepin-cd`镜像恢复之后快捷下载居然没了，一查原来deepin子目只匹配`1x`时代的镜像
> Update to Deepin 20

- help/_posts/1970-01-01-homebrew.md
brew 官方安装脚本又硬编码了 `HOMEBREW_CORE_GIT_REMOTE`，改为从环境变量读入。
> Fix git remotes in Homebrew help due to upstream changes

- help/_posts/1970-01-01-debian.md
经过实验，发现 jessie 的 sources.list 并没有 jessie-backports，如果使用时直接复制黏贴提供的命令会导致 HttpError404.
https://ftp.debian.org/debian/dists/
https://mirrors.tuna.tsinghua.edu.cn/debian/dists/
> Delete backports for debian jessie

- help/_posts/2021-03-11-opensuse.md
upstream now fix the missing content in backports repo, that fixed https://github.com/tuna/issues/issues/1269
including a note for 15.3 users to ensure correct repo enabled
version before 15.2 have officially EOL, so bump version
minor change to repo alias, make it match the official naming
also minor tweak to command style
> Update help for openSUSE Leap 15.3

- geninfo/genisolist.ini
This PR adds more Fedora ISO images to the image download list.
JSON manifest generated by the script will be something like this:
```json
[
{
"distro": "Fedora",
"category": "os",
"urls": [
{
"name": "34 (x86_64, Everything netinst)",
"url": "/fedora/releases/34/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-34-1.2.iso"
},
{
"name": "34 (x86_64, Live CD with LXDE)",
"url": "/fedora/releases/34/Spins/x86_64/iso/Fedora-LXDE-Live-x86_64-34-1.2.iso"
},
{
"name": "34 (x86_64, Live CD with LXQt)",
"url": "/fedora/releases/34/Spins/x86_64/iso/Fedora-LXQt-Live-x86_64-34-1.2.iso"
},
{
"name": "34 (x86_64, Live CD with i3)",
"url": "/fedora/releases/34/Spins/x86_64/iso/Fedora-i3-Live-x86_64-34-1.2.iso"
},
{
"name": "34 (x86_64, Live CD with standard workstation desktop environment)", …
```
> GenISOList: Add more Fedora ISO images.

- geninfo/genisolist.py
This avoids stashing & applying changes to root each time when updating the mirror-web repository.
> Allow to override root in command-line

- geninfo/genisolist.py
The sort() here without reversing is not consistent with the sort() in
parseSection. This effectively puts oldest images first which is not
desirable.
> Reverse sorting of images

- help/_posts/1970-01-01-homebrew.md
Good morning TUNA maintainers,
For macOS Homebrew users,
```shell
git -C "$(brew --repo homebrew/command-not-found)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-command-not-found.git
```
that `homebrew/command-not-found` is available in TUNA mirror upstream, however is not updated in the auto-setup script.
This PR added the `homebrew/command-not-found` to the auto-setup script, both the replace and reset, to enable the manual replace and reset work.
> add homebrew/command-not-found to auto tap script

- geninfo/genisolist.ini
镜像站首页之前在 e081e35968383bca92ddcf6c06213bd1b05565f0 提交中增加了 Wireshark 前端链接。
但由于 https://github.com/tuna/issues/issues/1160 反馈以及 Wireshark 已不在此站发布新版软件的软件包，因此在 e93aa3bd2140ae4d4b1f6228e0a6ff1a144e8704 取消了 Wireshark 前端链接。
考虑到在 https://github.com/tuna/issues/issues/1164 已经完成了对 Wireshark 官方镜像的添加，因此本 PR 中恢复了镜像站首页的 Wireshark 前端链接，便于中国大陆用户快速、安全的下载 Wireshark 系列软件。
> Re-Add wireshark in frontend

- help/_posts/1970-01-01-homebrew.md
1. 重新在首次安装 Homebrew / Linuxbrew 时即使用 bottle 镜像。
2. 更新检查 tap 是否存在条件：将 `grep` 改为 `bash` 自带的字符串匹配。
3. 添加 Homebrew/command-not-found 在 Linux 上的帮助。
4. 带变量的字符串添加双引号。
> Update docs for Homebrew

- help/_posts/2019-07-23-kicad.md
详细说明查看 KiCad 社区官网  https://www.kicad.org/blog/2021/10/Avoid-links-to-former-kicad-domain/
> 修正 KiCad 网址

- help/_posts/2017-08-10-CTAN.md
增加了 CTAN 概述，以及主要 TeX 发行版的安装和镜像配置方法。
> 这份文档原本写给南京大学镜像站（完整版还没更新到网页上）。考虑到下半年就来你清了，顺手贡献过来：D
> 更新 CTAN 镜像帮助

- help/_posts/1970-01-01-gitlab-runner.md
- help/_posts/1970-01-01-ros2.md
- help/_posts/1970-01-01-ubuntu-ports.md
- help/_posts/1970-01-01-ubuntu.md
- help/_posts/2016-06-19-virtualbox.md
本来我想把 `#apt-template` 放到`_include` 里，各个 `help/_post/*.md` 只做引用；
结果发现每个软件仓库支持的系统版本会有细微差异，例如大多数项目还没发现 Ubuntu 22.04 LTS 发布了。
仔细想了想，我还是去 apt 那边提 patch 让 apt 自己支持 `$releasever` 吧，这样比较彻底 XD
> help: add debian bullseye and ubuntu jammy

- help/_posts/1970-01-01-docker-ce.md
- help/_posts/1970-01-01-termux.md
1. 将不再安全的apt-key改为官方文档使用的gpg -dearmor (see https://github.com/tuna/issues/issues/1413)
2. 修改termux软件包地址为/apt/pacname形式
> docker文档不再使用apt-key及termux软件包地址修改

- help/_posts/1970-01-01-ros2.md
ROS2 没有 i386 的版本，原来的版本不指定 arch，会导致 apt update 的时候出现 404 错误，  
因此加入了 `[arch=$(dpkg --print-architecture)]` 这一项，和官方文档同步。  
另外，根据较新的[官方文档](https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html)，已经不再使用 `apt-key` 了，所以这里也进行了相应的改动。（另请参考 tuna/issues#1413）
> Update ROS2 Document

- help/_posts/1970-01-01-pypi.md
参考原站的大小写（[https://pypi.org/](https://pypi.org/)），将全小写（`pypi`）改为原站的拼写（`PyPI`）。
> 修改PyPI帮助文档中PyPI的大小写

- help/_posts/1970-01-01-ros.md
- add ubuntu 20.04 (focal) and debian 10 (buster)
> Update ROS document

- help/_posts/1970-01-01-docker-ce.md
Docker provides a convenience script at https://get.docker.com/ to install Docker into development environments non-interactively.
Ref: https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script
> Add get.docker.com

- help/_posts/1970-01-01-pypi.md
The `--extra-index-url` option allows the user to configure multiple index urls, thus balancing the load.
> [pypi] add guidelines for configuring multiple index urls

- geninfo/genisolist.ini
- geninfo/genisolist.py
This PR introduce a breaking change in `/genisoinfo`. It's expected to compare generated results from mirror site.
> genisoinfo: ubuntu and id in python script

- help/_posts/1970-01-01-elpa.md
1. add gnu-devel and nongnu-devel to the table
2. add short descriptions in the section "关于 ELPA 的选择"
> help: elpa: add gnu-devel and nongnu-devel

- help/_posts/1970-01-01-homebrew.md
* brew 4.0.22 移除了对homebrew-cask-drivers仓库的支持，关于仓库的设置命令均会报错，因此移除文档内对此仓库的设置命令。 参考Homebrew/brew#15535
报错内容：
`
Error: homebrew/cask-drivers was deprecated. This tap is now empty and all its contents were either deleted or migrated.
`
* 置顶所有有关brew版本更新引起的镜像变化的注解
* 增加Linuxbrew下homebrew-services仓库的设置命令。经过测试，homebrew-services已在systemd/Linux下可用。
* 测试环境：Debian 11, Ubuntu 20.04, Ubuntu 22.04, Fedora 37
* 测试bottle：syncthing，unbound
* 分离<复原仓库上游>章节下Homebrew与Linuxbrew共用的codeblock，以免引起误解
> homebrew 镜像帮助更新

- help/_posts/1970-01-01-pypi.md
Ref: https://python-poetry.org/docs/cli#options-13
Options `--default` and `--secondary` have been
> Deprecated in favor of --priority.
> help: pypi: update poetry command options

- help/_posts/1970-01-01-gitlab-ce.md
Bookworm has been synchronized. However, help is outdated.
> help: gitlab-ce: add bookworm

- _config.yml
Since [Jekyll 3.5.0](https://github.com/jekyll/jekyll/releases/tag/v3.5.0), plugins have been added to config key as replacement for gems in https://github.com/jekyll/jekyll/pull/5130. This patch resolves a deprecation warning "Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly." when executing `bundle exec jekyll serve`.
> Replace deprecated gems with plugins

- geninfo/genisolist.ini
从 [1.2.0](https://github.com/iina/iina/releases/tag/v1.2.0) 开始，IINA 通用打包同时支持 x86_64 和 ARM
如果将来他们分开打包，这里还需要修改
> Update type of IINA

- geninfo/genisolist.py
distutils would be removed in Python 3.12, and we only need the version part. It's a better idea to vendor it instead of asking users to install a new package.
Also, LooseVersion is modified to be more robust.
Co-authored-by: Keyu Tao taoky@ustclug.org
> feat: vendor LooseVersion and some improvements and integrate version.py into genisolist.py
