tuna/mirror-web

index.html
Fix issue#6
remove the <a> tag and implement the cursor with a class
=> Fix issue#6

wiki/aosp.md
这就是刚刚提 issue 的时候说到的改动 repo init 的部分不用包含。
我也注意到你们有同名但扩展名不一样的 aosp.wiki 文件，
但我不清楚你们使用的 wiki 格式，所以没有改。请告知一下，
我另外 open 一个 pull request
另外，你们的 issue 页面不能在线回复
=> revise step to modify the manifest.xml file instead of the git config

index.html, wiki/hackage.md
=> add 'hackage.md'

dockerfile
Usage: `docker run --name=jekyll -p 4000:4000 -v $(pwd):/src <this image name/id>`
=> add dockerfile

_posts/help/1970-01-01-Fedora.md
Fix for https://github.com/tuna/issues/issues/67
=> add help pages for Fedora

_posts/help/1970-01-01-docker.md, _posts/help/1970-01-01-ubuntu.md
- Add Ubuntu Yakkety.
- Set Ubuntu Xenial as default.
- Add Ubuntu Xenial.
- Remove Ubuntu Utopic, Vivid, Wily and Debian Strech.
=> Update help doc.

_posts/help/1970-01-01-ubuntu.md
=> Update Ubuntu mirror help doc.

_posts/help/1970-01-01-homebrew.md
Forget the homebrew science and python
=> fix(homebrew): Fix the homebrew science and python

_posts/help/2017-01-12-bioconductor.md
add Bioconductor mirror use manual. See issue https://github.com/tuna/issues/issues/189.
=> Bioconductor doc

_posts/help/2017-01-17-CRAN.md
=> add CRAN mirror use help.

_includes/footer.html
=> fix footer display when device size is middle

_posts/help/1970-01-01-lineageos.md
添加LineageOS源码同步异常的解决方法
对应的issue：
https://github.com/tuna/issues/issues/226
https://github.com/tuna/issues/issues/250
=> 添加LineageOS源码同步异常的解决方法

_posts/help/1970-01-01-pypi.md
add config path according to https://pip.pypa.io/en/stable/user_guide/#configuration
=> pip config path

_posts/help/2017-01-17-CRAN.md, _posts/help/2017-08-10-CTAN.md
- 新增 CTAN 帮助
- 在 CRAN 帮助中改正中英文之间的空格，并把超链接移至正文
=> add help for CTAN and update for CRAN

_posts/help/2017-07-20-grafana.md
=> feat: add help for Grafana

_posts/help/1970-01-01-lineageos.md
从lineage-15.0开始，cm.xml被更名为lineage.xml
=> Update for new source

_posts/help/1970-01-01-anaconda.md
https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/
=> Fix a format issue

_posts/help/1970-01-01-aosp.md
Signed-off-by: youxi <testyouxi@sina.com>
=> add for resuming from break-point

_data/mirror_desc.json, _posts/help/2017-12-29-gentoo-portage.md, _posts/help/2017-12-29-gentoo-prefix-portage.md
=> Add help for gentoo-portage and gentoo-portage-prefix

_posts/help/1970-01-01-lineageos.md
do NOT change the remote of github
=> update the help of lineageOS

_posts/help/2018-09-28-anthon.md
The following changes since commit b4b0fc99429638d77af255d98aa445eb07aa1209:
Fix typo in pypi help (2018-09-21 22:19:46 +0800)
are available in the Git repository at:
https://github.com/AOSC-Dev/mirror-web anthon-doc
for you to fetch changes up to 1cdcc941397c1b3cee1afbdc8e88fc3d4408ae6f:
anthon: add mirror help (2018-09-28 15:34:14 +0800)
----------------------------------------------------------------
Junde Yhi (1):
anthon: add mirror help
_posts/help/2018-09-28-anthon.md | 23 +++++++++++++++++++++++
1 file changed, 23 insertions(+)
create mode 100644 _posts/help/2018-09-28-anthon.md
=> anthon: add mirror help

_posts/help/2019-02-15-grafana.md
See https://github.com/tuna/issues/issues/511
Also https://github.com/tuna/tunasync-scripts/pull/28
=> grafana: upstream release model changed

_data/mirror_desc.json, _posts/help/2019-03-18-arch4edu.md
增加了 ARM 的支持~
（同时改了archlinuxcn的一个逗号。。。）
=> Updated info for arch4edu

_posts/help/1970-01-01-pypi.md
=> Add hint to use this mirror to upgrade pip

geninfo/genisolist.ini
This depends on tuna/tunasync-scripts#29
=> add nixos-images to genisolist

_posts/help/1970-01-01-raspbian.md
使用 raspbian 源还需要修改 /etc/apt/sources.list.d/raspi.list 文件
=> modify the help of the raspbian

_posts/help/2019-05-03-qubesos.md
Help for https://github.com/tuna/issues/issues/552
=> Add Qubes OS doc

_posts/help/1970-01-01-raspbian.md
fix link description to CC-3.0 link in the help/respbian page
=> help/respbian fix link description to CC-3.0 link

_posts/help/2019-03-18-arch4edu.md
added instructions to import gpg key
=> updated help for arch4edu

_posts/help/1970-01-01-gitlab-ce.md, _posts/help/1970-01-01-raspbian.md
Also fix a bug in gitlab-ce help
=> Add raspbian buster to raspbian help

_posts/help/1970-01-01-homebrew.md
Allow homebrew changes from any directory and remove mirrors of empty homebrew taps.
=> Update homebrew instructions

_posts/help/1970-01-01-termux.md
Termux在Android P上使用TUNA源会出现报错，在此给出修复方式
=> Give instructions to fix termux upgrade error

_posts/help/1970-01-01-anaconda.md
add free channel and others. add tips for Windows user when creating `.condarc`.
=> update help for anaconda

_includes/head.html
=> HTML Title: Respect site.title and site.brand if set

_posts/help/1970-01-01-gitlab-runner.md
add Ubuntu 18.04 for gitlab-runner install configuration
=> add Ubuntu 18.04 for gitlab-runner help

_data/options.yml, _posts/help/2019-02-17-nix.md
This is not yet tested. Probably merge after first mirroring finishes and basic usage is confirmed to work.
=> Add new Nix-related documentation

_posts/help/1970-01-01-flutter-sdk.git.md, _posts/help/2019-02-25-dart-pub.md, _posts/help/2019-02-27-flutter.md
cc/ @z4yx 
Hi Yuxiang: I've updated the pages about the Flutter mirrors, please review and let me know if you have any questions.
Thanks,
-Luke
=> Update the Flutter-related mirror intro pages.

_posts/help/1970-01-01-flutter-sdk.git.md, _posts/help/2019-02-25-dart-pub.md, _posts/help/2019-02-27-flutter.md
cc/ @z4yx 
Hi Yuxiang: I've updated the words about the flutter-sdk.git mirror.
Thanks!
-Luke
=> typo fix for Flutter mirror docs.

_posts/news/2020-05-02-bfsu-mirror.md
=> [news] announcing the presence of bfsu mirror

_posts/help/1970-01-01-stackage.md
=> update stackage config

_data/options.yml, _posts/help/2020-05-25-julia-releases.md, _posts/help/2020-05-25-julia.md, geninfo/genisolist.ini
添加 [[镜像请求] Julia：General registry](https://github.com/tuna/issues/issues/837) 中关于 julia 以及 julia-releases 这两个镜像的帮助文档
不太确定 `genisoinfo.ini` 的填写是否正确，可能需要你们检查一下
@findmyway @Roger-Luo 关于使用文档的内容你们觉得有什么需要补充或者修改的么？
=> add documentation for julia and julia-releases

_posts/help/2020-05-25-julia-releases.md
=> fix julia-releases download url

_posts/help/2020-05-25-julia-releases.md, _posts/help/2020-05-25-julia.md
* 介绍了如何使用 `JuliaZH` 来让镜像切换变得更简单
* 收集了一些社区里关于镜像的使用常常提到的问题
cc: @Roger-Luo @findmyway
=> add FAQ section and introduce JuliaZH

_data/options.yml, _posts/help/1970-01-01-raspbian.md, geninfo/genisolist.ini
=> Raspbian 改名 Raspberry Pi OS

geninfo/genisolist.ini
As @happyaron commented in #198 .
=> Add download link for Debian netinst with firmware

_layouts/help.html, static/js/help.es6
=> 隐藏不存在的镜像的帮助

help/_posts/2019-02-17-nix.md
`nix-channel --add` without explicit channel name doesn't really work...
=> nix: Fix channel commands

help/_posts/1970-01-01-archlinuxarm.md
没有懒人包的情况下 按照思维惯性输入了好几次 archlinuxcn 后来才反应过来（（
所以弄了个帮助文档
=> 增加 Arch Linux ARM 仓库的帮助

_layouts/index.html
=> :bug: fix: remove space search

help/_posts/2019-06-25-solus.md
=> update solus doc

geninfo/genisolist.ini
=> add solus to distro list

geninfo/genisolist.ini
Ref to #227 
An ad-hoc fix though.
=> Change from vlc-desktop to two separate section, win and macosx

geninfo/genisolist.ini
Add apps of `github-release` to isoinfo
**Reviews on the correctness of regex should be done** before merge since there is no local verification.
Further PR on `github-release` folder would be done; and similar for other common apps of other folder.
=> New apps isoinfo

geninfo/genisolist.ini
Fix problems in #229 
Add Git-For-Win and FreeCAD
Fully tested.
=> New apps isoinfo again

help/_posts/1970-01-01-homebrew.md, help/_posts/2020-12-29-CPAN.md
添加 CPAN 镜像的设置帮助
(Homebrew 帮助只是统一了一下中英文标点和执行了 markdownlint，checkout 的时候自动带到了本 branch)
=> Add help for CPAN

.gitignore, README.md, help/_posts/1970-01-01-mongodb.md
update MongoDB document
add file .DS_Store to .gitignore
edit README.md (url example)
--
更新了下 MongoDB 的文档
把 .DS_Store 扔进了 .gitignore
改了下 README 表单选择的链接（原来的404了）
另外参考：
https://github.com/tuna/issues/issues/1149
=> update MongoDB document

static/css/style.scss
Add `test: true` in `static/js/browser-update.js $buoop` to preview.
=> Add style for browser-update prompt

help/_posts/1970-01-01-homebrew-bottles.md, help/_posts/1970-01-01-homebrew.md, help/_posts/1970-01-01-linuxbrew-bottles.md
Update docs for Homebrew installation from https://github.com/Homebrew/install/pull/534.
=> Update docs for Homebrew

help/_posts/1970-01-01-openmediavault.md
related:
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues/51
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/pull/53
https://github.com/openmediavault/openmediavault/pull/988
=> improve openmediavault help

help/_posts/1970-01-01-msys2.md
=> update msys2 help

help/_posts/2021-05-25-influxdata.md
Add the help document of influxdata.
=> Add help document of influxdata

help/_posts/2021-07-14-ubuntu-cloud-images.md
=> 建立ubuntucloudimages使用帮助

help/_posts/1970-01-01-mysql.md
Add debain 11 and ubuntu 20.04 LTS help
=> Add debain 11 and ubuntu 20.04 LTS help

help/_posts/1970-01-01-proxmox.md
=> proxmox: apt add bullseye(Debian 11)

help/_posts/2018-09-28-anthon.md
The current AOSC OS apt-gen-list has been completely rewritten and the old usage is now obsolete, this Pull Request will update the apt-gen-list to the new usage
=> anthon: update help document

help/_posts/1970-01-01-raspbian.md
=> help: raspbian: fix whitespace

help/_posts/1970-01-01-termux.md
see https://github.com/tuna/issues/issues/1460
=> 修改termux软件包分类

help/_posts/1970-01-01-termux.md
=> 对termux使用帮助明添加不同版本的说明

help/_posts/1970-01-01-voidlinux.md
Voidlinux changed it's default official repository thus the command should be modified
voidlinux更改了默认官方repository，需要修改相关sed命令
=> help: update voidlinux official repository

help/_posts/1970-01-01-docker-ce.md
如题，官方文档使用`dpkg --print-architecture`简化操作
=> 跟进docker官方文档更改

help/_posts/1970-01-01-adoptium.md
upstream: https://adoptium.net/zh-CN/installation/linux/
同时部分修复 https://github.com/tuna/issues/issues/1413
=> Adoptium 跟进上游文档更改

README.md, help/_posts/1970-01-01-ubuntu.md
Fix readme.md typo.
Add command for replacing http://.*archive.ubuntu.com and http://.*security.ubuntu.com to https://{{ site.hostname }}.
=> update readme.md and 1970-01-01-ubuntu.md

geninfo/genisolist.ini
=> genisoinfo: update vscodium

help/_posts/1970-01-01-ubuntu.md
=> change link to help page

help/_posts/1970-01-01-openmediavault.md
=> update omv version

help/_posts/2022-08-22-elasticsearch.md
=> add elasticsearch help doc

help/_posts/2022-11-14-kali.md
Ref: https://mirrors.ustc.edu.cn/help/kali.html
=> Add Kali help

help/_posts/1970-01-01-homebrew.md
=> homebrew: add notes for `HOMEBREW_API_DOMAIN`

geninfo/genisolist.py
The changes are authored by @yaoge123 & @njulug. 
Origin: https://raw.githubusercontent.com/nju-lug/NJU-Mirror-Configs/main/scripts/genisolist/genisolist.py
=> Allow local testing of genisoinfo via rsync

help/_posts/1970-01-01-anaconda.md
[DeepModeling](deepmodeling.com) is a popular AI-assisted scientific computing open source community. Currently, most of its softwares are hosted in the `deepmodeling` conda channel.
=> Add deepmodeling to default conda channels

_layouts/index.html, static/js/index.es6
按下"/"键后聚焦搜索框
This commit addresses and closes #371
本提交解决并关闭#371
=> Focus on the searchbox when "/" key is pressed

_includes/head.html
Add RSS autodiscovery, relative to https://github.com/tuna/mirror-web/issues/387.
=> head: add RSS autodiscovery.

geninfo/genisolist.ini
Fix https://github.com/tuna/issues/issues/1809
=> Add F-Droid

help/_posts/1970-01-01-lineageOS.md
Reslove: https://github.com/tuna/issues/issues/1849
=> help: fix wrong lineage fetch url

help/_posts/1970-01-01-lineageOS.md
=> Revert "help: fix wrong lineage fetch url"

help/_posts/1970-01-01-pypi.md
See also:
mirrorz-org/mirrorz-docs:01890d4
mirrorz-org/mirrorz-docs#8
=> help(pypi): adapt the new `priority` option of `poetry`

help/_posts/1970-01-01-openmediavault.md
=> Update openmediavault version

geninfo/genisolist.ini
修正 https://github.com/tuna/mirror-web/pull/422 中的错误。
经过检查，发现所有的问题均为我的笔误，在路径前多加了“/“。
我对我的粗心大意表示抱歉。
=> 修正 #422 中的错误
